language: cpp

compiler:
  - clang

script:
  - make tests


notifications:
  email:
    recipients:
      - mz2325your_TAs_email@nyu.edu
    on_success: always
    on_failure: never

    recipients:
      - acs910@nyu.edu
    on_success: always
    on_failure: always  
